[project]
name = "ComfyUI-UsageMonitor"
description = "With this suit, you can see the resources monitor."
version = "1.30.2"
license = { file = "LICENSE" }
dependencies = ["torch", "nvidia-ml-py", "adlxpybind; sys_platform == 'win32'", "py-cpuinfo", "psutil"]

classifiers = [
  "Operating System :: OS Independent",
  "Environment :: GPU",
]

[project.urls]
Repository = "https://github.com/576576/ComfyUI-UsageMonitor"
Documentation = "https://github.com/576576/ComfyUI-UsageMonitor/blob/main/README.md"
"Bug Tracker" = "https://github.com/576576/ComfyUI-UsageMonitor/issues"

[tool.comfy]
PublisherId = "o576o"
DisplayName = "ComfyUI-UsageMonitor"
Icon = "https://raw.githubusercontent.com/576576/ComfyUI-UsageMonitor/main/assets/images/icon.png"
